### PR TITLE
"options" parameter support for multicheck, multicheck_inline, radio, radio_inline and select field types

### PR DESCRIPTION
**Pull request by ediamin**
Example: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#radio

Works only for multicheck, multicheck_inline, radio, radio_inline and select field types. When you select one of these field types, you'll get options to add your array key/value pair or simply the callback function.

screenshot from 2015-06-14 23 56 16

### CODE REVIEW

**Comment by hasinhayder** [comment]
That is an impressive pull request! Thanks a lot :)

Just one simple question before I merge it. Did you test what happen if someone clicks on the "+" or "X" beside a field which has a type of one of these fives, and has multiple options?

Please confirm :)

**Comment by ediamin** [comment]
Yes, I'm aware of the clone process of whole .form-element. When you click on "+", any html element with options will be removed after append.

**Comment by hasinhayder** [comment]
excellent - I am merging :)

thanks again

**Comment by ediamin** [comment]
You're welcome bro :)

**Pull request merged**
